worker_processes auto;
pid /tmp/nginx.pid;
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;

    # Railway logging
    access_log /dev/stdout;
    error_log /dev/stderr;

    server {
        # Valid port will be injected via envsubst
        listen $PORT;
        root /app/public;

        index index.php;

        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            include /etc/nginx/fastcgi_params;
        }

        # Deny access to sensitive files
        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}
